# Generated by Django 4.0.7 on 2022-08-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HitcountHitCount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hits', models.IntegerField()),
                ('modified', models.DateTimeField()),
                ('object_pk', models.IntegerField()),
            ],
            options={
                'db_table': 'hitcount_hit_count',
                'managed': False,
            },
        ),
    ]
