
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch master"
      if [ ! -z "master" -a -d "cloudblog-api-terraform-config/environments/master/" ]; then
        cd cloudblog-api-terraform-config/environments/master
        echo "run init"
        terraform init
        echo "run validate"
        terraform validate
        echo "run plan"
        terraform plan -out terraform.plan
        terraform apply -auto-approve terraform.plan
      else
        for dir in cloudblog-api-terraform-config/environments/*/
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFOM PLAN ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init
          terraform validate
          terraform plan || exit 1
          cd ../../
        done
      fi


- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"